use serde::{Deserialize, Serialize};

#[repr(u8)]
#[derive(Copy, Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum Positions {
    A1,
    B1,
    C1,
    D1,
    E1,
    F1,
    G1,
    H1,
    A2,
    B2,
    C2,
    D2,
    E2,
    F2,
    G2,
    H2,
    A3,
    B3,
    C3,
    D3,
    E3,
    F3,
    G3,
    H3,
    A4,
    B4,
    C4,
    D4,
    E4,
    F4,
    G4,
    H4,
    A5,
    B5,
    C5,
    D5,
    E5,
    F5,
    G5,
    H5,
    A6,
    B6,
    C6,
    D6,
    E6,
    F6,
    G6,
    H6,
    A7,
    B7,
    C7,
    D7,
    E7,
    F7,
    G7,
    H7,
    A8,
    B8,
    C8,
    D8,
    E8,
    F8,
    G8,
    H8,
}

impl Positions {
    pub fn to_index(&self) -> u8 {
        *self as u8
    }

    pub fn from_index(index: u8) -> Option<Positions> {
        match index {
            0 => Some(Positions::A1),
            1 => Some(Positions::B1),
            2 => Some(Positions::C1),
            3 => Some(Positions::D1),
            4 => Some(Positions::E1),
            5 => Some(Positions::F1),
            6 => Some(Positions::G1),
            7 => Some(Positions::H1),
            8 => Some(Positions::A2),
            9 => Some(Positions::B2),
            10 => Some(Positions::C2),
            11 => Some(Positions::D2),
            12 => Some(Positions::E2),
            13 => Some(Positions::F2),
            14 => Some(Positions::G2),
            15 => Some(Positions::H2),
            16 => Some(Positions::A3),
            17 => Some(Positions::B3),
            18 => Some(Positions::C3),
            19 => Some(Positions::D3),
            20 => Some(Positions::E3),
            21 => Some(Positions::F3),
            22 => Some(Positions::G3),
            23 => Some(Positions::H3),
            24 => Some(Positions::A4),
            25 => Some(Positions::B4),
            26 => Some(Positions::C4),
            27 => Some(Positions::D4),
            28 => Some(Positions::E4),
            29 => Some(Positions::F4),
            30 => Some(Positions::G4),
            31 => Some(Positions::H4),
            32 => Some(Positions::A5),
            33 => Some(Positions::B5),
            34 => Some(Positions::C5),
            35 => Some(Positions::D5),
            36 => Some(Positions::E5),
            37 => Some(Positions::F5),
            38 => Some(Positions::G5),
            39 => Some(Positions::H5),
            40 => Some(Positions::A6),
            41 => Some(Positions::B6),
            42 => Some(Positions::C6),
            43 => Some(Positions::D6),
            44 => Some(Positions::E6),
            45 => Some(Positions::F6),
            46 => Some(Positions::G6),
            47 => Some(Positions::H6),
            48 => Some(Positions::A7),
            49 => Some(Positions::B7),
            50 => Some(Positions::C7),
            51 => Some(Positions::D7),
            52 => Some(Positions::E7),
            53 => Some(Positions::F7),
            54 => Some(Positions::G7),
            55 => Some(Positions::H7),
            56 => Some(Positions::A8),
            57 => Some(Positions::B8),
            58 => Some(Positions::C8),
            59 => Some(Positions::D8),
            60 => Some(Positions::E8),
            61 => Some(Positions::F8),
            62 => Some(Positions::G8),
            63 => Some(Positions::H8),
            _ => None,
        }
    }
}
